Repository vishalverma9572/QuizMaster, pull requests merged in 2024-10, with the labels that each got.

#22 Added heading on createtest and taketest pages
  quiz-maker/src/Components/CreateTest.js
  quiz-maker/src/Components/TakeTest.css
  quiz-maker/src/Components/TakeTest.js
Labels: hacktoberfest, hacktoberfest-accepted

#41 feat: Improve backend in controller
  backend/controllers/quizController.js
  backend/controllers/userController.js
  backend/db/connectDb.js
  backend/index.js
  backend/middleware/auth.js
  backend/package-lock.json
  backend/routes/quizRouter.js
  backend/routes/userRouter.js
Labels: under review

#58 Solved : Resolve the negative timing error while creating a quiz and fixing some UI issues #28
  quiz-maker/src/Components/CreateTest.css
  quiz-maker/src/Components/CreateTest.js
Labels: under review

#51 Add old password field to profile page
  backend/controllers/userController.js
  quiz-maker/src/Components/Profile.js
Labels: hacktoberfest, priority

#57 Homepage design update
  quiz-maker/src/Components/Home.css
  quiz-maker/src/Components/Home.js
Labels: under review

#83 feature: added zod input validation + fixed merge conflicts
  backend/controllers/quizController.js
  backend/controllers/userController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/userRouter.js
  backend/validators/validations.js
  quiz-maker/src/Components/CreateTest.js
  quiz-maker/src/Components/EditQuiz.js
Labels: under review

#126 implemented loading sign and automatic scrolling on take test page
  package-lock.json
  quiz-maker/src/Components/TakeTest.css
  quiz-maker/src/Components/TakeTest.js
Labels: hacktoberfest, hacktoberfest-accepted
